config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  root 'posts#index'
  resources :users, only: [:show]
resources :posts, only: [:new, :create, :index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :title, presence: true, length: { maximum: 20 }
  validates :body, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :authenticate_user!, except: %i[index show]
  def index
    @posts = Post.all
  end

  def new
    @post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      flash[:notice] = 'Post was successfully created'
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def check_login(post)
    "Author: #{post.user.username}" if signed_in?
  end

  def check_errors(_post)
    @post.errors.any?
  end

  def check_user_login
    if user_signed_in?
      render 'form'
    else
      aredirect_to new_session_path
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag image_path('favicon.png') %>
    <title>Connect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="header">
      <nav class="navbar">
        <div class="navbar-brand">
          <%= link_to root_path do %>
            <%= image_tag('logo.png', width: '100') %>
          <% end %>
        </div>
        <% if user_signed_in? %>
          <%= link_to "#{current_user.username}", edit_user_registration_path, class: 'btn btn-info' %>
          <%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'btn btn-info' %>
        <% else %>
          <%= link_to 'Login', new_user_session_path %>
        <% end %>
      </nav>
    </header>
    <main class="container">
        <% if flash[ :notice] %>
          <div class="alert alert-success" role="alert">
            <%= notice %>
          </div>
        <% end %>
        <% if flash[ :alert]%>
          <div class="alert alert-success" role="alert">
            <%= alert %>
          </div>
        <% end %>
      <%= yield %>
    </main>
    <footer></footer>
  </body>
</html>

app/views/posts/_form.html.erb
<% if alert %>
	<div class='alert alert-danger'>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
        </button>
		<%= alert %>
	</div>
<% end %>

<%= form_with model:@post, local: true do |f|%>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true, autocomplete: 'title', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, autofocus: true, autocomplete: 'body', class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit 'submit', class: 'btn btn-success' %>
    <%= link_to 'Back to posts listing', posts_path %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div class="container">
  <p>
    <%= link_to 'Create new post', new_post_path, class: 'btn btn-primary' %>
  </p>
  <% @posts.each do |post|%>
  <div class="card container">
    <div class="card-body ">
      <h5 class="card-title"><%=post.title%></h5>
        <small class="text-muted"><%= check_login(post) %></small>
      <p class="card-text"><%=post.body%></p>
    </div>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<h1>Create a New Post</h1>

  <% check_errors(@post)%>
    <ul>
    <% @post.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <%end%>
    </ul>

<%= check_user_login %>